import asyncio
import re
from config import settings
from models.report import FinalReport
from models.ticket import TicketRequest

try:
    from github import Github, GithubException
    PYGITHUB_AVAILABLE = True
except ImportError:
    PYGITHUB_AVAILABLE = False


async def create_pr(report: FinalReport, ticket: TicketRequest) -> str:
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _sync_create_pr, report, ticket)


def _sync_create_pr(report: FinalReport, ticket: TicketRequest) -> str:
    if not PYGITHUB_AVAILABLE:
        raise RuntimeError("PyGithub not installed")
    if not settings.GITHUB_TOKEN:
        raise RuntimeError("GITHUB_TOKEN not configured")

    g = Github(settings.GITHUB_TOKEN)
    repo = g.get_repo(f"{settings.GITHUB_REPO_OWNER}/{settings.GITHUB_REPO_NAME}")

    branch_name = f"triagent/{report.job_id[:8]}"
    default_branch = repo.default_branch
    source = repo.get_branch(default_branch)

    # Create branch
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=source.commit.sha,
        )
    except GithubException:
        pass  # Branch already exists

    # Infer file name from ticket
    module_name = _slugify(ticket.title)
    lang_ext = {"python": "py", "javascript": "js", "java": "java", "go": "go"}.get(ticket.language, "py")

    # Write implementation
    impl_path = f"triagent/{module_name}.{lang_ext}"
    _upsert_file(repo, branch_name, impl_path, report.final_code, f"[TriAgent] Add {module_name} implementation")

    # Write tests
    test_path = f"tests/test_{module_name}.{lang_ext}"
    _upsert_file(repo, branch_name, test_path, report.test_suite, f"[TriAgent] Add tests for {module_name}")

    # Write security report
    security_md = _format_security_report(report, ticket)
    _upsert_file(repo, branch_name, f"docs/security_{module_name}.md", security_md, "[TriAgent] Add security report")

    # Create PR
    severity_counts = {}
    for f in report.security_findings:
        severity_counts[f.severity] = severity_counts.get(f.severity, 0) + 1

    pr_body = f"""## 🤖 TriAgent Automated Code Review

**Ticket:** {ticket.title}
**Language:** {ticket.language}
**Rounds taken:** {report.rounds_taken}
**Confidence Score:** {report.confidence_score}/10 {'🟢' if report.confidence_score >= 8 else '🟡' if report.confidence_score >= 5 else '🔴'}

### Test Results
{'✅ All tests passed' if report.all_tests_passed else '❌ Some tests failed'}

### Security Findings Summary

| Severity | Count |
|----------|-------|
| CRITICAL | {severity_counts.get('CRITICAL', 0)} |
| HIGH | {severity_counts.get('HIGH', 0)} |
| MEDIUM | {severity_counts.get('MEDIUM', 0)} |
| LOW | {severity_counts.get('LOW', 0)} |
| INFO | {severity_counts.get('INFO', 0)} |

### Security Findings Detail

| OWASP ID | Title | Score |
|----------|-------|-------|
{''.join(f"| {f.owasp_id} | {f.title} | {f.score} |" + chr(10) for f in report.security_findings) or '| — | No findings | — |'}

> Generated by [TriAgent](https://github.com/akashnandy11/stadium) — The AI Code Review Squad
"""

    pr = repo.create_pull(
        title=f"[TriAgent] {ticket.title}",
        body=pr_body,
        head=branch_name,
        base=default_branch,
    )
    return pr.html_url


def _upsert_file(repo, branch: str, path: str, content: str, message: str):
    try:
        existing = repo.get_contents(path, ref=branch)
        repo.update_file(path, message, content, existing.sha, branch=branch)
    except Exception:
        repo.create_file(path, message, content, branch=branch)


def _slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    return text.strip("_")[:50]


def _format_security_report(report: FinalReport, ticket: TicketRequest) -> str:
    lines = [
        f"# Security Report: {ticket.title}",
        f"\n**Job ID:** `{report.job_id}`",
        f"**Confidence Score:** {report.confidence_score}/10",
        f"**Rounds:** {report.rounds_taken}",
        "\n## Findings\n",
    ]
    if not report.security_findings:
        lines.append("✅ No security issues found.\n")
    else:
        for f in report.security_findings:
            lines.append(f"### [{f.severity}] {f.title}")
            lines.append(f"- **OWASP:** {f.owasp_id}")
            lines.append(f"- **Score:** {f.score}/10")
            if f.line_number:
                lines.append(f"- **Line:** {f.line_number}")
            lines.append(f"- **Description:** {f.description}\n")
    return "\n".join(lines)
